---
  - name: Ensuring gpg is installed
    package:
      name: gpg
      state: present
    when: proxmox_install

  - name: Adding Apt Keys
    apt_key:
      id: 7BF2812E8A6E88E0
      url: "http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg"
    when: proxmox_install

  - name: Checking proxmox repos
    include: repos.yml

  - name: Update apt cache
    apt:
      update_cache: yes

  # As per https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_Buster#Install_Proxmox_VE_packages
  # Be aware, you must set the IP in hosts as per https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_Buster#Install_a_standard_Debian_Buster_.28amd64.29
  - name: Install proxmox
    package:
      name:
        - proxmox-ve
        - postfix
        - open-iscsi
      state: present
    when: proxmox_install

  # installing proxmox-ve causes it to re-instate the enterprise repo, so we have to check again
  - name: Re-checking proxmox repos
    include: repos.yml
    when: proxmox_install

  - name: Create VM's
    include: vms.yml
    with_items: "{{ proxmox_vms }}"
