---
- name: Setup sources
  template:
    src: "{{ item }}.list.j2"
    dest: "/etc/apt/sources.list.d/{{ item }}.list"
    mode: "0660"
    owner: root
    group: root
  with_items:
    - pve-community
    - pve-enterprise

- name: Adding Apt Keys
  apt_key:
    id: E2EF0603
    url: "http://download.proxmox.com/debian/proxmox-ve-release-5.x.gpg"

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400