---
- name: Check Enterprise repository
  apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/pve stretch pve-enterprise
    state: "{{ proxmox_is_community | ternary('absent', 'present') }}"
    filename: 'pve-enterprise'
    update_cache: "{{ proxmox_is_community | ternary(false, true) }}"

- name: Check Community repository
  apt_repository:
    repo: deb http://download.proxmox.com/debian/pve stretch pve-no-subscription
    state: "{{ proxmox_is_community | ternary('present', 'absent') }}"
    filename: 'pve-community'
    update_cache: "{{ proxmox_is_community | ternary(true, false) }}"
